directory: # Input file paths
  "/home/krueger_l/Dokumente/Metabarcoding/Metabarcoding/FRANZ_processing/demux_trnL/01_RawData"
output: # Working folder for output
  "/home/krueger_l/Dokumente/Metabarcoding/trnl_TEST"

paired: true

protein_coding: false

adapter_trimming_options:
  - "-g CGAAATCGGTAGACGCTACG"
  - "-G CCATTGAGTCTCTGCACCTATC"
  - "-O 23"
merge_options:
  - "--fastq_allowmergestagger"
  - "--fastq_minovlen 100"
  - "--fastq_maxdiffs 15"
  - "--fastq_eeout"
filter_options:
  - "--fastq_maxee 1.0"
  - "--fastq_minlen 100"
  - "--fastq_maxlen 800"
  - "--fastq_maxns 0"
  - "--fasta_width 0"
derep1_options: # TODO obligatory options should be hardcoded
  - "--strand plus"
  - "--sizeout"
  - "--fasta_width 0"

# Coding sequences
coding:
  code: 5 # NCBI translation table number
  hmm: null # Path to HMM of target protein sequence to screen translations

# Denoising - Update these default values after viewing diagnostics
denoising:
  alpha : 5    # Clustering parameter alpha used for Unoise or DnoisE
  minsize : 8  # Minimum sequence cluster size to retain
  method: 'dnoise' # either "unoise" or "dnoise"
  dnoise_opts:
    frame: 3 # Codon position (1, 2, or 3) of the first base
    alpha_range :        # Range of alpha to test for entropy ratio diagnostics
      [1,2,3,4,5,6,7,8,9,10]
    minsize_range:       # Range of minsize to test for entropy ratio diagnostics
      [2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100]

community_table_options:
  - "--id 0.97"
  - "--strand plus"

# Taxonomic classification
direct_dbs:
  - "/mnt/data/databases/bcd_trnl/trnl_viridiplantae_de.fa"
  - "/mnt/data/databases/bcd_trnl/trnl_viridiplantae_eu.fa"
hierarchical_db: "/mnt/data/databases/bcd_trnl/trnl_viridiplantae_all.fa"
classification_threshold: "0.97"
hierarchical_threshold: "0.8"

