workdir: # Path to working folder
  "test"
input:   # Folder with input files - path is relative to workdir
  "input"
paired: true           # true or false only
protein_coding: true   # true or false only

adapter_trimming_options:
  - "-g CCNGAYATRGCNTTTYCCNCG"
  - "-G TANACYTCNGGRTGNCCRAARAAYCA"
  - "-O 23"
merge_options:
  - "--fastq_allowmergestagger"
  - "--fastq_minovlen 100"
  - "--fastq_maxdiffs 15"
  - "--fastq_eeout"
filter_options:
  - "--fastq_maxee 1.0"
  - "--fastq_minlen 100"
  - "--fastq_maxlen 800"
  - "--fastq_maxns 0"
  - "--fasta_width 0"
derep1_options: # TODO obligatory options should be hardcoded
  - "--strand plus"
  - "--sizeout"
  - "--fasta_width 0"

# Coding sequences only
coding:
  code: 5   # NCBI translation table number
  frame: 3  # Expected codon position (1, 2, or 3) of the first base
  hmm:      # HMM to screen translations, path relative to workdir
    "db/bold_arthropod.hmm"

# Denoising - Update these default values after viewing diagnostics
denoising:
  alpha : 5        # Clustering parameter alpha used for Unoise or DnoisE
  minsize : 8      # Minimum sequence cluster size to retain
  method: 'dnoise' # either "unoise" or "dnoise"

# Options for DnoisE
dnoise_opts:
  alpha_range :    # Range of alpha to test for entropy ratio diagnostics
    [1,5,10]
  minsize_range:   # Range of minsize to test for entropy ratio diagnostics
    [2,10]

community_table_options:
  - "--id 0.97"
  - "--strand plus"

treeprog: "fasttree" # Options: fasttree, iqtree

# Taxonomic classification
direct_dbs: # Path is relative to workdir
  - "db/bold_coi-5p_test.fasta"
hierarchical_db:
  "db/bold_coi-5p_test.fasta"
classification_threshold: "0.90"
hierarchical_threshold: "0.8"

