extra_fn_clean_exts:
    - type: 'remove'
      pattern: '.concat.R1'
      module:
        - cutadapt
    - type: 'remove'
      pattern: '.concat.R2'
      module:
        - cutadapt

custom_data:
  tax_classification:
    section_name: "Taxonomic classification"
    description: "ASVs classified in each stage of the taxonomic classification"
    file_format: "tsv"
    plot_type: "table"
sp:
  tax_classification:
    fn: "stats_mqc.*"
