extra_fn_clean_exts:
    - type: 'remove'
      pattern: '.concat.R1'
      module:
        - cutadapt
    - type: 'remove'
      pattern: '.concat.R2'
      module:
        - cutadapt

custom_data:
  tax_classification:
    file_format: "tsv"
    section_name: "Taxonomic classification"
    plot_type: "table"

sp:
  tax_classification:
    fn: "stats_mqc.*"

