directory: "/home/krueger_l/Dokumente/Metabarcoding/Metabarcoding/FRANZ_processing/demux_trnL/01_RawData"
output: "/home/krueger_l/Dokumente/Metabarcoding/trnL_results_test_2"
00_length_threshold: 100
01_adapter_trimming_options:
  - "-g CGAAATCGGTAGACGCTACG"
  - "-G CCATTGAGTCTCTGCACCTATC"
  - "-O 20"
  - "--pair-adapters"
  - "--action=trim"
  - "--trimmed-only"
02_trimmomatic_options:
  - "SLIDINGWINDOW:4:12"
  - "MINLEN:100"
  - "-phred33"
03_vsearch_merge_options:
  - "--fastq_allowmergestagger"
  - "--fastq_maxdiffs 10"
  - "--fastq_maxee 2"
  - "--fastq_minmergelen 100"
  - "--fastq_maxmergelen 300"
  - "--fastq_maxns 1"
09_community_table_options:
  - "--id 0.97"
  - "--threads 8"
  - "--sizein"
  - "--maxaccepts 0"
  - "--maxrejects 0"
11_direct_dbs:
  - "/mnt/data/databases/trnl.plantae.de_complete_sintax_db.fa"
  - "/mnt/data/databases/trnl.plantae.eu_complete_sintax_db.fa"
11_hierarchical_db: "/mnt/data/databases/trnL_CD_nr_sintax.fasta"
11_threshold: "0.97"
threads: 8
mqc_report: true
taxonomy: true
concat: true
