directory: "/home/krueger_l/Dokumente/Metabarcoding/Metabarcoding/FRANZ_processing/demux_trnL/01_RawData"
output: "/home/krueger_l/Dokumente/Metabarcoding/trnL_results_DE"
00_length_threshold: "100"
01_adapter_trimming_options:
  - "-g CGAAATCGGTAGACGCTACG"
  - "-G CCATTGAGTCTCTGCACCTATC"
  - "-O 20"
  - "--pair-adapters"
  - "--action=retain"
  - "--trimmed-only"
01_adapter_fw: "CGAAATCGGTAGACGCTACG"
01_adapter_rv: "CCATTGAGTCTCTGCACCTATC"
01_min_overlap: 20
01_trimmed_only: true
02_trimmomatic_options:
  - "SLIDINGWINDOW:4:12"
  - "MINLEN:100"
  - "-phred33"
03_vsearch_merge_options:
  - "--fastq_allowmergestagger"
  - "--fastq_maxdiffs 10"
  - "--fastq_maxee 2"
  - "--fastq_minmergelen 100"
  - "--fastq_maxmergelen 300"
  - "--fastq_maxns 1"
09_otu_table_options:
  - "--id 0.97"
  - "--threads 8"
  - "--sizein"
  - "--maxaccepts 0"
  - "--maxrejects 0"
11_database: "/mnt/data/databases/its2.plantae.de_complete_sintax_db.fa"
11_threshold: "0.8"
mqc_report: false
taxonomy: true
